### ISSUE TITLE
Error - Library files are corrupt 

### ISSUE THREAD

**Issue by noutram-old-uopaccount** [ARMmbed/mbed-client-for-azure#14]
### Description of defect
When building this project in Mbed Studio (it is one of the template projects), the button to "fix library" cannot seem to fetch azure-io-sdk-c

It says "Library files are corrupt"

I assume this is a submodule with the wrong URL, and I am able to work around this by cloning this submodule manually.

#### Target(s) affected by this defect ?
NUCLEO F429ZI

#### Toolchain(s) (name and version) displaying this defect ?
ARMC6

#### What version of Mbed-os are you using (tag or sha) ?
6.15.1

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)
Mbed Studio 1.4.3
Arm C6 6.16

#### How is this defect reproduced ?
Create a new project in Mbed Studio, and choose the Azure IoT Hub template.
Attempt to fix libraries.

**Comment by 0xc0170** [comment]
Is it this one: https://github.com/ARMmbed/mbed-client-for-azure/blob/master/azure-iot-sdk-c.lib (related to the issue) ?

The reference looks correct (I've checked if the commit exists, it does in the remote).

**Comment by noutram-old-uopaccount** [comment]
It would seem so. However, when I clone the [example](https://github.com/ARMmbed/mbed-client-for-azure), it reports "Corrupted Library" for the iot-sdk-c library.

**Comment by noutram** [comment]
> It would seem so. However, when I clone the [example](https://github.com/ARMmbed/mbed-client-for-azure), it reports "Corrupted Library" for the iot-sdk-c library.

Correction - when I import

**Comment by noutram-old-uopaccount** [comment]
![Screenshot 2021-12-13 131524](https://user-images.githubusercontent.com/4012184/145819348-2fe60a45-49f4-42ac-b7b1-33fe44729420.png)

**Comment by mcgordonite** [comment]
Hi @noutram, this is likely an issue with Mbed Studio. Some things to try:
- If you haven't already, delete the project from your workspace and re-import it from https://github.com/ARMmbed/mbed-os-example-for-azure.
- The cache for this library could be corrupt. For per-user installs on Windows, this will be in `%HOME%\AppData\Local\Mbed Studio\library-cache\github.com\azure`. Delete the azure-iot-sdk-c entry and re-import the project.
- Check the Mbed Studio logs: `%HOME%\AppData\Local\Mbed Studio\mbed-studio.log`.

**Comment by noutram-old-uopaccount** [comment]
ok, I will give that a try and report back

**Comment by noutram-old-uopaccount** [comment]
It appeared to be a corrupt cache. Interestring it happened on several student's computers as well
As you suggested, deleting the azure-iot-sdk-c entry from %HOME%\AppData\Local\Mbed Studio\library-cache\github.com\azure seemed to fix it.  I will pass the message on. Many thanks.
