### ISSUE TITLE
Apply azure-sdk-for-c for smaller ROM size

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/mbed-client-for-azure#8]
Current ROM size of mbed-os-example-for-azure seems too big for normal MCU platforms.
According to my evaluation based on the same NUMAKER_IOT_M487 platform:
 

- [azure-iot-preview](https://github.com/azure-rtos/azure-iot-preview/tree/master/azure_iot): ROM size is 131 KB without using heap.

- mbed-os-example-for-azure: ROM size is 368 KB

We forked & ported mbed-os-example-for-azure on NUMKAER_IOT_M487 in this [repo](https://github.com/OpenNuvoton/mbed-os-example-for-azure) , it could work but ROM size is too big.
So, I cross check with azure-iot-preview based on azure-sdk-for-c, this [M487 azure-iot-preview repo](https://github.com/OpenNuvoton/azure-getting-started/tree/nuvoton_azure_rtos/Nuvoton/M480/samples/demo_azure_iot/keil) is ROM size as small as 131 KB.
I used the same toolchain to build these 2 examples for Azure connection and the key factor is azure [azure-iot-sdk-c](https://github.com/Azure/azure-iot-sdk-c) v.s [azure-sdk-for-c](https://github.com/Azure/azure-sdk-for-c).

- Target :    NUMKAER_IOT_M487
- Toolchain: ARMCC6 (Keil)
- Mbed OS: both of v6.3.0
- How to reproduce: 
1. import https://github.com/OpenNuvoton/mbed-os-example-for-azure, then build by `$ mbed compile -m NUMAKER_IOT_M487 -t ARM`
1. Clone https://github.com/OpenNuvoton/azure-getting-started/, then git update sub modules. After that, to open Keil project to build https://github.com/OpenNuvoton/azure-getting-started/tree/nuvoton_azure_rtos/Nuvoton/M480/samples/demo_azure_iot/keil

So, is there any plan to apply azure-sdk-for-c to fulfill memory footprint of MCU level ?

**Comment by ciarmcom** [comment]
@cyliangtw it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by cyliangtw** [comment]
@ciarmcom , Sorry for late update
We forked & ported mbed-os-example-for-azure on NUMKAER_IOT_M487 in this [repo](https://github.com/OpenNuvoton/mbed-os-example-for-azure) , it could work but ROM size is too big.
So, I cross check with azure-iot-preview based on azure-sdk-for-c, this [M487 azure-iot-preview repo](https://github.com/OpenNuvoton/azure-getting-started/tree/nuvoton_azure_rtos/Nuvoton/M480/samples/demo_azure_iot/keil) is ROM size as small as 131 KB.
I used the same toolchain to build these 2 examples for Azure connection and the key factor is azure [azure-iot-sdk-c](https://github.com/Azure/azure-iot-sdk-c) v.s [azure-sdk-for-c](https://github.com/Azure/azure-sdk-for-c).

- Target :    NUMKAER_IOT_M487
- Toolchain: ARMCC6 (Keil)
- Mbed OS: both of v6.3.0
- How to reproduce: 
1. import https://github.com/OpenNuvoton/mbed-os-example-for-azure, then build by `$ mbed compile -m NUMAKER_IOT_M487 -t ARM`
1. Clone https://github.com/OpenNuvoton/azure-getting-started/, then git update sub modules. After that, to open Keil project to build https://github.com/OpenNuvoton/azure-getting-started/tree/nuvoton_azure_rtos/Nuvoton/M480/samples/demo_azure_iot/keil

**Comment by ciarmcom** [comment]
@cyliangtw it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by cyliangtw** [comment]
@ciarmcom , I updated this issue header with target, tool chain, OS version & how to reproduce info. .

**Comment by ciarmcom** [comment]
@cyliangtw it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@cyliangtw it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by cyliangtw** [comment]
transfer to https://github.com/ARMmbed/mbed-client-for-azure/issues/10
